import '@testing-library/jest-dom';

// Mock Telegram WebApp
Object.defineProperty(window, 'Telegram', {
  value: {
    WebApp: {
      initData: '',
      initDataUnsafe: {},
      version: '7.0',
      platform: 'web',
      colorScheme: 'light',
      themeParams: {},
      isActive: true,
      isExpanded: true,
      viewportHeight: 0,
      viewportStableHeight: 0,
      headerColor: '#ffffff',
      backgroundColor: '#ffffff',
      bottomBarColor: '#ffffff',
      safeAreaInset: { top: 0, bottom: 0, left: 0, right: 0 },
      contentSafeAreaInset: { top: 0, bottom: 0, left: 0, right: 0 },
      ready: () => {},
      expand: () => {},
      close: () => {},
      setHeaderColor: () => {},
      setBackgroundColor: () => {},
      setBottomBarColor: () => {},
      enableClosingConfirmation: () => {},
      disableClosingConfirmation: () => {},
      isVersionAtLeast: () => true,
      onEvent: () => {},
      offEvent: () => {},
      openLink: () => {},
      openTelegramLink: () => {},
      openInvoice: () => {},
      showPopup: () => {},
      showAlert: () => {},
      showConfirm: () => {},
      showScanQrPopup: () => {},
      closeScanQrPopup: () => {},
      requestWriteAccess: () => {},
      requestContact: () => {},
      readTextFromClipboard: () => {},
      enableVerticalSwipes: () => {},
      disableVerticalSwipes: () => {},
      requestFullscreen: () => {},
      exitFullscreen: () => {},
      lockOrientation: () => {},
      unlockOrientation: () => {},
      addToHomeScreen: () => {},
      checkHomeScreenStatus: () => {},
      setEmojiStatus: () => {},
      requestEmojiStatusAccess: () => {},
      shareToStory: () => {},
      shareMessage: () => {},
      downloadFile: () => {},
      MainButton: {
        text: '',
        color: '#2481cc',
        textColor: '#ffffff',
        isVisible: false,
        isActive: true,
        hasShineEffect: false,
        isProgressVisible: false,
        show: () => {},
        hide: () => {},
        enable: () => {},
        disable: () => {},
        showProgress: () => {},
        hideProgress: () => {},
        setText: () => {},
        setParams: () => {},
        onClick: () => {},
        offClick: () => {},
      },
      SecondaryButton: {
        text: '',
        type: 'default',
        position: 'bottom',
        show: () => {},
        hide: () => {},
        enable: () => {},
        disable: () => {},
        setText: () => {},
        setParams: () => {},
        onClick: () => {},
        offClick: () => {},
      },
      BackButton: {
        isVisible: false,
        show: () => {},
        hide: () => {},
        onClick: () => {},
        offClick: () => {},
      },
      HapticFeedback: {
        impactOccurred: () => {},
        notificationOccurred: () => {},
        selectionChanged: () => {},
      },
      CloudStorage: {
        setItem: () => {},
        getItem: () => {},
        getItems: () => {},
        removeItem: () => {},
        removeItems: () => {},
        getKeys: () => {},
      },
      BiometricManager: {},
      LocationManager: {},
      Accelerometer: {},
      Gyroscope: {},
      DeviceOrientation: {},
    },
  },
  writable: true,
});
